In [ ]:
# importing the required libraries 
import pandas as pd 
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.model_selection import  train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.model_selection import cross_val_score


In [5]:
df = pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset3/main/weatherAUS.csv')

In [6]:
df

Date Location  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0     2008-12-01   Albury     13.4     22.9       0.6          NaN       NaN   
1     2008-12-02   Albury      7.4     25.1       0.0          NaN       NaN   
2     2008-12-03   Albury     12.9     25.7       0.0          NaN       NaN   
3     2008-12-04   Albury      9.2     28.0       0.0          NaN       NaN   
4     2008-12-05   Albury     17.5     32.3       1.0          NaN       NaN   
...          ...      ...      ...      ...       ...          ...       ...   
8420  2017-06-21    Uluru      2.8     23.4       0.0          NaN       NaN   
8421  2017-06-22    Uluru      3.6     25.3       0.0          NaN       NaN   
8422  2017-06-23    Uluru      5.4     26.9       0.0          NaN       NaN   
8423  2017-06-24    Uluru      7.8     27.0       0.0          NaN       NaN   
8424  2017-06-25    Uluru     14.9      NaN       0.0          NaN       NaN   

     WindGustDir  WindGustSpeed WindDir9am  ... Humidity9am  Humidity3pm  \
0              W           44.0          W  ...        71.0         22.0   
1            WNW           44.0        NNW  ...        44.0         25.0   
2            WSW           46.0          W  ...        38.0         30.0   
3             NE           24.0         SE  ...        45.0         16.0   
4              W           41.0        ENE  ...        82.0         33.0   
...          ...            ...        ...  ...         ...          ...   
8420           E           31.0         SE  ...        51.0         24.0   
8421         NNW           22.0         SE  ...        56.0         21.0   
8422           N           37.0         SE  ...        53.0         24.0   
8423          SE           28.0        SSE  ...        51.0         24.0   
8424         NaN            NaN        ESE  ...        62.0         36.0   

      Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  \
0          1007.7       1007.1       8.0       NaN     16.9     21.8   
1          1010.6       1007.8       NaN       NaN     17.2     24.3   
2          1007.6       1008.7       NaN       2.0     21.0     23.2   
3          1017.6       1012.8       NaN       NaN     18.1     26.5   
4          1010.8       1006.0       7.0       8.0     17.8     29.7   
...           ...          ...       ...       ...      ...      ...   
8420       1024.6       1020.3       NaN       NaN     10.1     22.4   
8421       1023.5       1019.1       NaN       NaN     10.9     24.5   
8422       1021.0       1016.8       NaN       NaN     12.5     26.1   
8423       1019.4       1016.5       3.0       2.0     15.1     26.0   
8424       1020.2       1017.9       8.0       8.0     15.0     20.9   

      RainToday  RainTomorrow  
0            No            No  
1            No            No  
2            No            No  
3            No            No  
4            No            No  
...         ...           ...  
8420         No            No  
8421         No            No  
8422         No            No  
8423         No            No  
8424         No           NaN  

[8425 rows x 23 columns]

In [36]:
df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset3/main/weatherAUS.csv')
X = df.iloc[:,[1,2,3,4,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21]].values
Y= df.iloc[:,-1].values

In [37]:
print (X)

[['Albury' 13.4 22.9 ... 16.9 21.8 'No']
 ['Albury' 7.4 25.1 ... 17.2 24.3 'No']
 ['Albury' 12.9 25.7 ... 21.0 23.2 'No']
 ...
 ['Uluru' 5.4 26.9 ... 12.5 26.1 'No']
 ['Uluru' 7.8 27.0 ... 15.1 26.0 'No']
 ['Uluru' 14.9 nan ... 15.0 20.9 'No']]


In [38]:
print(Y)

['No' 'No' 'No' ... 'No' 'No' nan]


In [39]:
Y = Y.reshape(-1,1) # used to change 1d list into 2d list 

In [40]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 [nan]]


# Dealing with invalid dataset

In [41]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='most_frequent')

In [44]:
X=imputer.fit_transform(X)
Y=imputer.fit_transform(Y)

In [46]:
print(X)

[[1 13.4 22.9 ... 16.9 21.8 0]
 [1 7.4 25.1 ... 17.2 24.3 0]
 [1 12.9 25.7 ... 21.0 23.2 0]
 ...
 [9 5.4 26.9 ... 12.5 26.1 0]
 [9 7.8 27.0 ... 15.1 26.0 0]
 [9 14.9 19.0 ... 15.0 20.9 0]]


In [47]:
print(Y)

[['No']
 ['No']
 ['No']
 ...
 ['No']
 ['No']
 ['No']]


# Encoding Dataset

In [57]:
from sklearn.preprocessing import LabelEncoder
LE1 = LabelEncoder()
X[:,0]=LE1.fit_transform(X[:,0])
LE2 = LabelEncoder()
X[:,4]=LE2.fit_transform(X[:,4])
LE3 = LabelEncoder()
X[:,6]=LE3.fit_transform(X[:,6])
LE4 = LabelEncoder()
X[:,7]=LE4.fit_transform(X[:,7])
LE5 = LabelEncoder()
X[:,-1]=LE5.fit_transform(X[:,-1])
LE6 = LabelEncoder()
Y = LE6.fit_transform(Y)



In [58]:
print(X)

[[ 1.          0.04039106 -0.15101108 ... -0.15006358 -0.10175254
   0.        ]
 [ 1.         -1.07478085  0.20800875 ... -0.09661746  0.318031
   0.        ]
 [ 1.         -0.05253993  0.30592325 ...  0.58036664  0.13332624
   0.        ]
 ...
 [ 9.         -1.44650482  0.50175225 ... -0.93393991  0.62027515
   0.        ]
 [ 9.         -1.00043606  0.51807133 ... -0.47074026  0.60348381
   0.        ]
 [ 9.          0.31918404 -0.78745533 ... -0.48855563 -0.25287462
   0.        ]]


In [60]:
print(Y)

[0 0 0 ... 0 0 0]


# Feature Scaling 

In [61]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [62]:
print(X)

[[-1.51577598  0.04039106 -0.15101108 ... -0.15006358 -0.10175254
  -0.55609919]
 [-1.51577598 -1.07478085  0.20800875 ... -0.09661746  0.318031
  -0.55609919]
 [-1.51577598 -0.05253993  0.30592325 ...  0.58036664  0.13332624
  -0.55609919]
 ...
 [ 1.01389522 -1.44650482  0.50175225 ... -0.93393991  0.62027515
  -0.55609919]
 [ 1.01389522 -1.00043606  0.51807133 ... -0.47074026  0.60348381
  -0.55609919]
 [ 1.01389522  0.31918404 -0.78745533 ... -0.48855563 -0.25287462
  -0.55609919]]


# Splitting dataset into Training set and Test set

In [63]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=0)

In [64]:
print(X_train)

[[ 0.06526852  0.8024252  -0.18364925 ...  0.40221293 -0.15212657
  -0.55609919]
 [ 1.64631302  0.46787363 -0.37947825 ...  0.06372088 -0.4879534
  -0.55609919]
 [-1.51577598 -1.33498763 -0.15101108 ... -0.86267843  0.03257819
  -0.55609919]
 ...
 [-0.25094038 -0.75881547 -0.90168891 ... -0.70234009 -0.87415426
  -0.55609919]
 [ 1.33010412  1.08121818  0.28960417 ...  0.93667407  0.28444832
   1.79824035]
 [ 0.38147742 -0.4800225  -1.50549499 ... -0.7557862  -1.34431183
   1.79824035]]


In [65]:
print(Y_train)

[0 0 0 ... 1 0 1]


# Training the Model

In [66]:
from sklearn.ensemble import RandomForestClassifier
cl = RandomForestClassifier(n_estimators=100,random_state=0)
cl.fit(X_train,Y_train)


RandomForestClassifier(random_state=0)

In [67]:
cl.score(X_train,Y_train)

0.9998516320474777

In [68]:
y_pred = cl.predict(X_test)

In [69]:
print(y_pred)

[0 0 0 ... 1 0 0]


In [70]:
y_pred = LE6.inverse_transform(y_pred) 
Y_test

In [71]:
print(y_pred)

['No' 'No' 'No' ... 'Yes' 'No' 'No']


In [72]:
print(Y_test)

[1 0 0 ... 1 0 0]


In [73]:
Y_test = LE6.inverse_transform(Y_test)

In [74]:
print(Y_test)

['Yes' 'No' 'No' ... 'Yes' 'No' 'No']


In [75]:
Y_test = Y_test.reshape(-1,1)
y_pred = y_pred.reshape(-1,1)

In [79]:
df = np.concatenate((Y_test,y_pred),axis=1)
dataframe = pd.DataFrame(df,columns=['Rain On Tommorrow ' , 'Prediction of Rain'])

In [81]:
print(df)

[['Yes' 'No']
 ['No' 'No']
 ['No' 'No']
 ...
 ['Yes' 'Yes']
 ['No' 'No']
 ['No' 'No']]


In [83]:
print(dataframe)

     Rain On Tommorrow  Prediction of Rain
0                   Yes                 No
1                    No                 No
2                    No                 No
3                    No                 No
4                   Yes                Yes
...                 ...                ...
1680                Yes                 No
1681                 No                 No
1682                Yes                Yes
1683                 No                 No
1684                 No                 No

[1685 rows x 2 columns]


In [82]:
dataframe.to_csv('prediction.csv')

# Calculating Accuracy


In [85]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test,y_pred)

0.8991097922848664

In [86]:
dataframe.to_csv('prediction.csv')

The accuracy score is very good approx 90% with RandomForestClassifier 